BXB-4418 xcode15 cxx flags
airtimemedia/boringssl pull request #23
Opened 2023-10-21 04:46 UTC by bhanu-cantina

In file included from boringssl/crypto/fipsmodule/bcm.c:43:
boringssl/crypto/fipsmodule/bn/generic.c:597:51: error: argument 'a' of type 'const uint64_t[8]' (aka 'const unsigned long long[8]') with mismatched bound [-Werror,-Warray-parameter]
void bn_sqr_comba8(BN_ULONG r[16], const BN_ULONG a[8]) {
boringssl/crypto/fipsmodule/bn/internal.h:292:51: note: previously declared as 'const uint64_t[4]' (aka 'const unsigned long long[4]') here
void bn_sqr_comba8(BN_ULONG r[16], const BN_ULONG a[4]); 
1 error generated.

2023-10-21 05:59 UTC, artasano approved these changes

2023-10-21 09:06 UTC, jim-wong requested changes
Can you extend the comment to indicate that we're making this change to accommodate Xcode?

Something like:

```
# airtime: start (BXB-4418)
# Disable warnings to compile on macOS
...
# airtime: end (BXB-4418)

2023-10-23 07:11 UTC, bhanu-cantina commented
resolved comments

2023-10-23 07:57 UTC, jim-wong approved these changes

2023-10-23 08:20 UTC, merged